---
title: "Lab2"
author: "Cale Bible"
date: "2025-09-04"
output: 
  html_document: 
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tasks

## Task 1

```{r}
getwd()
list.files()
```

## Task 2
```{r}
mpg <- read.csv("EPAGAS.csv")
head(mpg)
```
## Task 3
```{r}
mpgv <- mpg$MPG
z <- (mpgv-mean(mpgv))/sd(mpgv)
# To get potential outliers, we can plot it using a box plot.
mycol = ifelse(abs(z)>3, "Red",
        ifelse(abs(z)>=2 &abs(z)<=3,"Blue", "Black"))  
mypch = ifelse(abs(z)>3, 20,
        ifelse(abs(z)>=2 &abs(z)<=3,21, 22))
library(lattice)
# Blue symbolizes possible outliers, while red symbolizes the actual outliers.
#FIXME: Add title.
dotplot(mpg$MPG,col=mycol)
```

## Task 4

```{r}
library(ggplot2)
#FIXME: Add median line.
 ggplot(data = mpg, aes(x = "", y = MPG)) +
      geom_boxplot(, fill="black") +
      geom_vline(xintercept = median(mpg$MPG), color = "red", linetype = "dashed", size = 1) 
      coord_flip() +
      labs(title="MPG Distribution") +
      theme_minimal()
```
